// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketHive_MadCats.Server.Data;

#nullable disable

namespace TicketHive_MadCats.Server.MigrationsEventTicket
{
    [DbContext(typeof(EventTicketDbContext))]
    [Migration("20230409113943_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketHive_MadCats.Shared.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSrcs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxTickets")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 4, 9, 13, 39, 43, 815, DateTimeKind.Local).AddTicks(3504),
                            EventType = "TestEventType1",
                            ImageSrcs = "[\"/images/event images/image 1.avif\",\"/images/event images/image 2.avif\"]",
                            Location = "TestEvent1Location",
                            MaxTickets = 5,
                            Name = "TestEvent1",
                            TicketPrice = 100
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 4, 9, 13, 39, 43, 815, DateTimeKind.Local).AddTicks(3559),
                            EventType = "TestEventType2",
                            ImageSrcs = "[\"/images/event images/image 3.avif\",\"/images/event images/image 4.avif\"]",
                            Location = "TestEvent2Location",
                            MaxTickets = 2,
                            Name = "TestEvent2",
                            TicketPrice = 100
                        });
                });

            modelBuilder.Entity("TicketHive_MadCats.Shared.Models.TicketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventModelId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventModelId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventModelId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            EventModelId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 3,
                            EventModelId = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 4,
                            EventModelId = 2,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("TicketHive_MadCats.Shared.Models.TicketModel", b =>
                {
                    b.HasOne("TicketHive_MadCats.Shared.Models.EventModel", "EventModel")
                        .WithMany("Tickets")
                        .HasForeignKey("EventModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventModel");
                });

            modelBuilder.Entity("TicketHive_MadCats.Shared.Models.EventModel", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
